/*************************************************************
 * Copyright (c) 2015 Marcel Herd
 *
 * Distributed under the MIT License.
 *
 * The full license can be reviewed in the LICENSE file, 
 * distributed with this software.
 *************************************************************/
 
/**
 * This module defines commonly used constants.
 */
 
#define DEBUG true
 
#define GAME_MODE "SAMP-RACE"

#define DIALOG_LOGIN 1
#define DIALOG_REGISTRATION 2

#define COLOR_RED 0xFF0000FF

#define MIN_PASSWORD_LENGTH 8
#define MAX_PASSWORD_LENGTH 24

#define BCRYPT_COST 12