/*************************************************************
 * Copyright (c) 2015 Marcel Herd
 *
 * Distributed under the MIT License.
 *
 * The full license can be reviewed in the LICENSE file, 
 * distributed with this software.
 *************************************************************/
 
/**
 * This module defines commonly used constants.
 */
 
#define DEBUG true
 
#define GAME_MODE "SAMP-RACE"
 
#define MAX_PASSWORD_LENGTH 129

#define BCRYPT_COST 12