DROP TABLE IF EXISTS `samp`.`player`;

CREATE TABLE `samp`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(24) NOT NULL,
  `password` VARCHAR(129) NOT NULL,
  `money` INT ZEROFILL NOT NULL DEFAULT 0,
  `experience` INT ZEROFILL NOT NULL DEFAULT 0,
  `adminLevel` INT ZEROFILL NOT NULL DEFAULT 0,
  `banned` TINYINT(1) ZEROFILL NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC));