/*************************************************************
 * Copyright (c) 2015 Marcel Herd
 *
 * Distributed under the MIT License.
 *
 * The full license can be reviewed in the LICENSE file, 
 * distributed with this software.
 *************************************************************/
 
/**
 * This module defines the admin model.
 */
 
 enum ADMIN_MODEL
 {
	SUPPORTER = 1,
	MODERATOR = 2,
	ADMIN = 3,
	SUPERADMIN = 4
 }